// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7xllBG4bux-2R9MT6lCXQzJmwPzqdKhE',
    appId: '1:718174248692:web:591316be0e662e4bd588a1',
    messagingSenderId: '718174248692',
    projectId: 'auth-project-86b69',
    authDomain: 'auth-project-86b69.firebaseapp.com',
    storageBucket: 'auth-project-86b69.appspot.com',
    measurementId: 'G-LWEJG94V63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYJbWX20QkeNXhTFwNd_P5d8prYz6Tzbc',
    appId: '1:718174248692:android:8876f587191ee6dad588a1',
    messagingSenderId: '718174248692',
    projectId: 'auth-project-86b69',
    storageBucket: 'auth-project-86b69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-U5ixlejRxOZwLsd2kJx4Jczad9NAh0Y',
    appId: '1:718174248692:ios:d7750d9925b01ebdd588a1',
    messagingSenderId: '718174248692',
    projectId: 'auth-project-86b69',
    storageBucket: 'auth-project-86b69.appspot.com',
    iosBundleId: 'com.test.projectauthtest.projectAuthTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-U5ixlejRxOZwLsd2kJx4Jczad9NAh0Y',
    appId: '1:718174248692:ios:6c4c704f38290d70d588a1',
    messagingSenderId: '718174248692',
    projectId: 'auth-project-86b69',
    storageBucket: 'auth-project-86b69.appspot.com',
    iosBundleId: 'com.test.projectauthtest.projectAuthTest.RunnerTests',
  );
}
